trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
# Install .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
  displayName: 'Install .NET SDK'

# Restore Backend Dependencies
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/Server.csproj'
  displayName: 'Restore Backend Dependencies'

# Build Backend Project
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/Server.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore'
  displayName: 'Build Backend Project'

# Publish Backend Project
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/Server.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --no-restore'
    zipAfterPublish: true
  displayName: 'Publish Backend Project'

# Publish Backend Artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'backend-artifact'
    publishLocation: 'Container'
  displayName: 'Publish Backend Artifact'
  
#   # Deploy to Azure App Service
# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: '4P1'
#     appType: 'webApp'
#     appName: 'productServer'
#     package: '$(Build.ArtifactStagingDirectory)/drop/backend.zip'
#   displayName: 'Deploy Backend to Azure App Service'
