// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Server.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Server.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Category = "Clothes",
                            ImageUrl = "https://images.unsplash.com/photo-1594902876423-bfbd3f4cb935",
                            Name = "Jeans",
                            Price = 40
                        },
                        new
                        {
                            Id = 6,
                            Category = "Fruits",
                            ImageUrl = "https://www.bigbasket.com/media/uploads/p/xxl/40129358_1-fresho-banana-robusta.jpg",
                            Name = "Banana",
                            Price = 1
                        },
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            ImageUrl = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
                            Name = "Laptop",
                            Price = 1200
                        },
                        new
                        {
                            Id = 12,
                            Category = "Clothes",
                            ImageUrl = "https://images.unsplash.com/photo-1600185365005-6d1d02acdf04",
                            Name = "Sneakers",
                            Price = 50
                        },
                        new
                        {
                            Id = 3,
                            Category = "Electronics",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQPtqgtRPFysnPMlI3I3gOKV6wY7RyZ9hzsNecwy--WhyD17g50Zpk0aaQ3t_gKFnxQw8FKOsQnxC8j03py6vx92bM9omEAUrd0MNsJ3dQEZg11aFsfpwT1",
                            Name = "Headphones",
                            Price = 150
                        },
                        new
                        {
                            Id = 14,
                            Category = "Books",
                            ImageUrl = "https://images.unsplash.com/photo-1553729784-e91953dec042",
                            Name = "Book: ReactJS Guide",
                            Price = 30
                        },
                        new
                        {
                            Id = 13,
                            Category = "Groceries",
                            ImageUrl = "https://pureandsure.in/cdn/shop/files/broekn-rice_01549bc9-034b-45d1-9065-41a29613907d.jpg?v=1727177828",
                            Name = "Rice (1kg)",
                            Price = 2
                        },
                        new
                        {
                            Id = 8,
                            Category = "Fruits",
                            ImageUrl = "https://hips.hearstapps.com/hmg-prod/images/766/grapes-main-1506688521.jpg?crop=0.848xw:1xh",
                            Name = "Grapes",
                            Price = 5
                        },
                        new
                        {
                            Id = 7,
                            Category = "Fruits",
                            ImageUrl = "https://www.jiomart.com/images/product/original/590000025/orange-imported-1-kg-product-images-o590000025-p590000025-0-202410011652.jpg?im=Resize=(420,420)",
                            Name = "Orange",
                            Price = 2
                        },
                        new
                        {
                            Id = 9,
                            Category = "Clothes",
                            ImageUrl = "https://image.hm.com/assets/hm/8b/ea/8bea8bac07ed75596e5597f6d2997f07cfd81fac.jpg?imwidth=768",
                            Name = "T-Shirt",
                            Price = 20
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            ImageUrl = "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9",
                            Name = "Smartphone",
                            Price = 800
                        },
                        new
                        {
                            Id = 4,
                            Category = "Electronics",
                            ImageUrl = "https://images.unsplash.com/photo-1587829741301-dc798b83add3",
                            Name = "Keyboard",
                            Price = 100
                        },
                        new
                        {
                            Id = 11,
                            Category = "Clothes",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREZodCYpCCPz_Q4BDiFpxZJAhU1piEp998Hw&s",
                            Name = "Jacket",
                            Price = 60
                        },
                        new
                        {
                            Id = 5,
                            Category = "Fruits",
                            ImageUrl = "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce",
                            Name = "Apple",
                            Price = 1
                        },
                        new
                        {
                            Id = 15,
                            Category = "Books",
                            ImageUrl = "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f",
                            Name = "Book: JavaScript Mastery",
                            Price = 25
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Server.Models.OrderItem", b =>
                {
                    b.HasOne("Server.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Server.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
