// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250502053736_AddProductImageUrl3")]
    partial class AddProductImageUrl3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Server.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Server.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            ImageUrl = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
                            Name = "Laptop",
                            Price = 1200
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            ImageUrl = "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9",
                            Name = "Smartphone",
                            Price = 800
                        },
                        new
                        {
                            Id = 3,
                            Category = "Electronics",
                            ImageUrl = "https://images.unsplash.com/photo-1570466589027-b21817c6d177",
                            Name = "Headphones",
                            Price = 150
                        },
                        new
                        {
                            Id = 4,
                            Category = "Electronics",
                            ImageUrl = "https://images.unsplash.com/photo-1587829741301-dc798b83add3",
                            Name = "Keyboard",
                            Price = 100
                        },
                        new
                        {
                            Id = 5,
                            Category = "Fruits",
                            ImageUrl = "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce",
                            Name = "Apple",
                            Price = 1
                        },
                        new
                        {
                            Id = 6,
                            Category = "Fruits",
                            ImageUrl = "https://images.unsplash.com/photo-1574226516831-e1dff420e42e",
                            Name = "Banana",
                            Price = 1
                        },
                        new
                        {
                            Id = 7,
                            Category = "Fruits",
                            ImageUrl = "https://www.jiomart.com/images/product/original/590000025/orange-imported-1-kg-product-images-o590000025-p590000025-0-202410011652.jpg?im=Resize=(420,420)",
                            Name = "Orange",
                            Price = 2
                        },
                        new
                        {
                            Id = 8,
                            Category = "Fruits",
                            ImageUrl = "https://images.unsplash.com/photo-1615484477776-fb9d99dfb64c",
                            Name = "Grapes",
                            Price = 5
                        },
                        new
                        {
                            Id = 9,
                            Category = "Clothes",
                            ImageUrl = "https://images.unsplash.com/photo-1580894908361-0f13edb7cd5e",
                            Name = "T-Shirt",
                            Price = 20
                        },
                        new
                        {
                            Id = 10,
                            Category = "Clothes",
                            ImageUrl = "https://images.unsplash.com/photo-1594902876423-bfbd3f4cb935",
                            Name = "Jeans",
                            Price = 40
                        },
                        new
                        {
                            Id = 11,
                            Category = "Clothes",
                            ImageUrl = "https://images.unsplash.com/photo-1603164565087-77a16d42864d",
                            Name = "Jacket",
                            Price = 60
                        },
                        new
                        {
                            Id = 12,
                            Category = "Clothes",
                            ImageUrl = "https://images.unsplash.com/photo-1600185365005-6d1d02acdf04",
                            Name = "Sneakers",
                            Price = 50
                        },
                        new
                        {
                            Id = 13,
                            Category = "Groceries",
                            ImageUrl = "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f",
                            Name = "Rice (1kg)",
                            Price = 2
                        },
                        new
                        {
                            Id = 14,
                            Category = "Groceries",
                            ImageUrl = "https://images.unsplash.com/photo-1623271270835-98ee6b0fd5c9",
                            Name = "Sugar (1kg)",
                            Price = 1
                        },
                        new
                        {
                            Id = 15,
                            Category = "Groceries",
                            ImageUrl = "https://images.unsplash.com/photo-1597953689321-0b24b9c0d86b",
                            Name = "Flour (1kg)",
                            Price = 1
                        },
                        new
                        {
                            Id = 16,
                            Category = "Groceries",
                            ImageUrl = "https://images.unsplash.com/photo-1621517682370-df6c4470f80d",
                            Name = "Vegetable Oil (500ml)",
                            Price = 3
                        },
                        new
                        {
                            Id = 17,
                            Category = "Books",
                            ImageUrl = "https://images.unsplash.com/photo-1553729784-e91953dec042",
                            Name = "Book: ReactJS Guide",
                            Price = 30
                        },
                        new
                        {
                            Id = 18,
                            Category = "Books",
                            ImageUrl = "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f",
                            Name = "Book: JavaScript Mastery",
                            Price = 25
                        },
                        new
                        {
                            Id = 19,
                            Category = "Furniture",
                            ImageUrl = "https://images.unsplash.com/photo-1618531971792-e79d99987217",
                            Name = "Sofa",
                            Price = 400
                        },
                        new
                        {
                            Id = 20,
                            Category = "Furniture",
                            ImageUrl = "https://images.unsplash.com/photo-1603317657060-3ca2069ecb0b",
                            Name = "Dining Table",
                            Price = 250
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Server.Models.OrderItem", b =>
                {
                    b.HasOne("Server.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Server.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
